# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-18 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='Users',
        ),
    ]
